// DoctorBar.tsx

export const doctorList = [
  {
    id: 'D-1001',
    name: 'Dr. Sarah Johnson',
    specialty: 'Cardiology',
    experience: 12,
    gender: 'Female',
    hospital: 'City General Hospital',
    availability: '2025-11-29 10:30 AM',
    status: 'Available',
    rating: 4.9,
  },
  {
    id: 'D-1002',
    name: 'Dr. Michael Chen',
    specialty: 'Endocrinology',
    experience: 15,
    gender: 'Male',
    hospital: 'Metro Health Center',
    availability: '2025-11-29 09:00 AM',
    status: 'Available',
    rating: 4.7,
  },
  {
    id: 'D-1003',
    name: 'Dr. Aisha Patel',
    specialty: 'Neurology',
    experience: 8,
    gender: 'Female',
    hospital: 'Central Medical Institute',
    availability: '2025-11-29 02:15 PM',
    status: 'Booked',
    rating: 4.8,
  },
  {
    id: 'D-1004',
    name: 'Dr. Rajesh Kumar',
    specialty: 'Cardiology',
    experience: 20,
    gender: 'Male',
    hospital: 'Heart Care Clinic',
    availability: '2025-12-01 11:00 AM',
    status: 'Available',
    rating: 4.95,
  },
  {
    id: 'D-1005',
    name: 'Dr. Elena Rodriguez',
    specialty: 'Pulmonology',
    experience: 10,
    gender: 'Female',
    hospital: 'Lung Health Center',
    availability: '2025-12-02 04:45 PM',
    status: 'Available',
    rating: 4.6,
  },
  {
    id: 'D-1006',
    name: 'Dr. David Kim',
    specialty: 'Nephrology',
    experience: 18,
    gender: 'Male',
    hospital: 'Kidney Care Specialists',
    availability: '2025-12-03 12:00 PM',
    status: 'On Call',
    rating: 4.85,
  },
  {
    id: 'D-1007',
    name: 'Dr. Priya Sharma',
    specialty: 'Rheumatology',
    experience: 14,
    gender: 'Female',
    hospital: 'Joint Health Clinic',
    availability: '2025-12-04 09:30 AM',
    status: 'Available',
    rating: 4.7,
  },
  {
    id: 'D-1008',
    name: 'Dr. Robert Taylor',
    specialty: 'Pulmonology',
    experience: 22,
    gender: 'Male',
    hospital: 'Respiratory Care Center',
    availability: '2025-12-05 03:00 PM',
    status: 'High Demand',
    rating: 4.9,
  },
  {
    id: 'D-2001',
    name: 'Dr. Lisa Wong',
    specialty: 'General Medicine',
    experience: 9,
    gender: 'Female',
    hospital: 'Family Health Clinic',
    availability: '2025-11-29 10:30 AM',
    status: 'upcoming',
    rating: 4.5,
  },
  {
    id: 'D-2002',
    name: 'Dr. Ahmed Hassan',
    specialty: 'Cardiology',
    experience: 16,
    gender: 'Male',
    hospital: 'Heart Specialists',
    availability: '2025-11-29 11:15 AM',
    status: 'upcoming',
    rating: 4.8,
  },
  {
    id: 'D-2003',
    name: 'Dr. Maria Garcia',
    specialty: 'Internal Medicine',
    experience: 11,
    gender: 'Female',
    hospital: 'Primary Care Center',
    availability: '2025-11-29 02:00 PM',
    status: 'completed',
    rating: 4.75,
  },
];
